services:

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - '/home/ec2-user/spree410/database/postgresql:/var/lib/postgresql/data'

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/data'

volumes:
  redis:
  postgres:
